services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d6r5omvdiees73c2nhk0-a.c123.render.com
      - key: DB_USER
        value: todouser
      - key: DB_PASSWORD
        value: xiYh4zF6CL1eKdEedArYynxksHIxg6Zw
      - key: DB_NAME
        value: tododb_oefi
      - key: DB_PORT
        value: "5432"
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo.onrender.com
      - key: NODE_ENV
        value: production
